name: Run tests on pull request

on: [pull_request]

jobs:
    test:
        strategy:
            fail-fast: true
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                node-version: 18
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - run: pnpm i
            - run: npm run test
